import { join } from 'node:path'

/** Repo root (employee-manager-fe). */
export const repoRoot = join(import.meta.dir, '..')

/**
 * Build outputs and tool caches only — safe for `clean`.
 * Does not touch source, lockfile, .env, or public/.
 * `src/generated/` is OpenAPI codegen output (regenerated by `prebuild:app`).
 */
export const cleanPaths = [
  'dist',
  'dist-ssr',
  'src/generated',
  join('node_modules', '.tmp'),
  join('node_modules', '.vite'),
] as const

/** Removed only by `nuke` (after clean). */
export const nukeOnlyPaths = ['node_modules'] as const
